apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-app-VERSION
spec:
  replicas: 4
  selector:
    matchLabels:
      app: capstone-app
      version: "VERSION"
  template:
    metadata:
      labels:
        app: capstone-app
        version: "VERSION"
    spec:
      containers:
      - name: capstone-app
        image: sirvanci/capstone-app:VERSION
        ports:
        - containerPort: 80
