apiVersion: v1
kind: Service
metadata:
    name: loadbalancer
spec:
    type: LoadBalancer
    selector:
        app: capstone-app
    ports:
    - port: 80
      protocol: TCP
      targetPort: 80
    
    