apiVersion: v1
kind: Service
metadata:
    name: loadbalancer-blue
spec:
    type: LoadBalancer
    selector:
        app: capstone-app
        version: "VERSION"
    ports:
    - port: 80
      protocol: TCP
      targetPort: 80
    
    