apiVersion: v1
kind: Service
metadata:
    name: loadbalancer-green
spec:
    type: LoadBalancer
    selector:
        app: capstone-app
        version: "VERSION"
    ports:
    - port: 5000
      protocol: TCP
      targetPort: 80
    
    