# build environment
FROM node:15.0.0-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json 
COPY yarn.lock ./
RUN npm config set registry https://registry.npmjs.org/
RUN yarn install --immutable
COPY . ./
RUN yarn build

# production environment
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
